<a href="https://colab.research.google.com/github/shivumk111/MSK1/blob/master/SaravananML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

####**Hello World**

In [ ]:
print("Hello, World! How are You?")

Hello, World! How are You?


####**Datatypes**

In [ ]:
a = 12
type(a)

int

In [ ]:
type(True)

bool

In [ ]:
a, b, c = 1, 2, 3

a, b, c

(1, 2, 3)

In [ ]:
a = 11
print(a+2)
print(a-2)
print(a*2)
print(a/2)
print(a%2)
print(a//2)

13
9
22
5.5
1
5


In [ ]:
x, y = True, False
print(x and y)
print(x or y)
print(not y)
print( x & y)

False
True
True
False


In [ ]:
x, y =  1, 2

print(x<y)

True


In [ ]:
import random

a = [1, 2, 3, 4, 5]

b = random.choice(a)

print(b)

c = random.randint(1, 15)
print(c)

print(c in a)

1
15
False


####**Conditions**

In [ ]:
a, b  =  1, 2
if (a > b):
    print("a is higher")
elif a < b:
    print("b is higher")
else:
    print(" a == b")        

b


####**Loop**

In [ ]:
c = 0

while c < 5:
    print(c)
    c += 1

0
1
2
3
4


In [ ]:
for c in range(6):
    print(c)

0
1
2
3
4
5


In [ ]:
a = [1, 5, 9, 12]
for c in a:
    print(c)

1	 hi5	 hi9	 hi12	 hi

In [ ]:
for c in range(10, 0, -2):
    print(c)

10
8
6
4
2


####**String**

In [ ]:
a = 'Python'
b = ' is awesome!'
c= 1
d = '. '
print(a+b)

print(str(c) + d + a + b)

Python is awesome!
1. Python is awesome!


In [ ]:
print("This is  'a' = '{0}' and this is 'b' = '{1}'".format(a,b))

This is  'a' = 'Python' and this is 'b' = ' is awesome!'


In [ ]:
print(a.upper(),'\t' ,a.lower())

PYTHON 	 python


In [ ]:
print(b.rstrip())

 is awesome!


In [ ]:
print(b.replace('awesome', 'great'))

 is great!


In [ ]:
a = 'Python'
b = 'PYTHON'
print ( b in a.upper())

True


####**List**

In [ ]:
L = [ 1,  1.1 , 2 + 2j, True, None, 'Shiva']

L[len(L)-1] = "Python"

print(L)

[1, 1.1, (2+2j), True, None, 'Python']


In [ ]:
L.append('Shiva')

print(L)

print(L[-1])

[1, 1.1, (2+2j), True, None, 'Python', 'Shiva']
Shiva


In [ ]:
a = L.pop()
print(a, L)

Shiva [1, 1.1, (2+2j), True, None, 'Python']


In [ ]:
print(L[1:2])

[1.1]


In [ ]:
print(L[2:])

[(2+2j), True, None, 'Python']


In [ ]:
print(L[:])

[1, 1.1, (2+2j), True, None, 'Python']


In [ ]:
print(L[::-1])

['Python', None, True, (2+2j), 1.1, 1]


In [ ]:
a = [1, 2, 4, 5, 3]
a.sort()
print(a)

[1, 2, 3, 4, 5]


In [ ]:
L = ['Shiva', 'Rama', 'Krishnan']
L.sort()
print(L)


['Krishnan', 'Rama', 'Shiva']


In [ ]:

L = [1.1, 2.3, 5,5, 3.4]
L.sort()
print(L)

[1.1, 2.3, 3.4, 5, 5]


In [ ]:
L.reverse()
print(L)

[5, 5, 3.4, 2.3, 1.1]


In [ ]:
a =  [ 1, 5, 2, 3 , 4, 2, 3, 2]

print(a.count(2))

3


####**Tuple**

In [ ]:
t = (1, )
print(t, type(t))

(1,) <class 'tuple'>


In [ ]:
L = [ 1, 2, 3, 4]

t = tuple(L)

print(L, t, type(t))

[1, 2, 3, 4] (1, 2, 3, 4) <class 'tuple'>


####**Dictionary**


In [ ]:
d = {1: 'One', 2:'Two', 3: "Three", 2: "Four"}

print(d)

{1: 'One', 2: 'Four', 3: 'Three'}


In [ ]:
print(d[2])

Four


In [ ]:
d[2] = 'Two'
for key, value in d.items():
    print(key, value)

1 One
2 Two
3 Three


In [ ]:
d[4] = 'Four'
for key, value in d.items():
    print(key, value)

1 One
2 Two
3 Three
4 Four


In [ ]:
for key, value in d.items():
    print(key, value)

In [ ]:
d.pop(2)
print(d)

{1: 'One', 3: 'Three', 4: 'Four'}


####**try-except**

In [ ]:

try:
    print(z)
except:
    print('Something went wrong') 

Something went wrong


In [ ]:
z=9

try:
    print(z)
except:
    print('Something went wrong') 
finally:
    print('print me too')       

9
print me too


####**functions**


In [ ]:
def double_num(n):
    return n*2

In [ ]:
dn = double_num(10)

print(dn)

20


####**Which is fast**

In [ ]:
import time
t= tuple(range(3_00_00_000))

start = time.time()
td = map(lambda x: x*2, t)
end = time.time()
print('Time taken: ', end-start)

Time taken:  0.00011515617370605469


In [ ]:
import time
L= list(range(3_00_00_000))

start = time.time()
td = map(lambda x: x*2, L)
end = time.time()
print('Time taken: ', end-start)

Time taken:  9.512901306152344e-05


In [ ]:
abc = 1,000,000

In [ ]:
a b c = 1 2 3

SyntaxError: ignored

In [ ]:
str1="Stack of books"
print(len(str1))

14


In [ ]:
try:
  print(x)
except:
  print(""An exception occurred"")

####numpy**

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])

print(a)

[1 2 3]


In [ ]:
a.shape

(3,)

In [ ]:
a.ndim

1

In [ ]:
a.size

3

In [ ]:
a.itemsize

8

In [ ]:
a.dtype

dtype('int64')

In [ ]:
print(a[0])

1


In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
b.shape

(2, 3)

In [ ]:
c = np.ones((2, 3))
d = np.zeros((3, 2))

print(c)
print(d)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
e = np.random.randint((2, 10))

In [ ]:
print(e)

[0 3]


In [27]:
print(" \"hello\" ")

 "hello" 
